# Transaction data exploration

This notebook contains the initial exploration of the transaction dataset

## Objectives

- Verify that the development environment works correctly
- Review the basic structure of a pandas DataFrame
- Practise basic NumPy and pandas operations

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
print(f"NumPy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")

NumPy version: 2.5.0
Pandas version: 3.0.3

## First numpy array

Creation of a small array containing transactions amounts

In [9]:
amounts = np.array([12.50, 8.00, 19.75, 4.20, 31.00])
amounts

array([12.5 ,  8.  , 19.75,  4.2 , 31.  ])

In [10]:
amounts * 1.10

array([13.75 ,  8.8  , 21.725,  4.62 , 34.1  ])

## First pandas dataframe

Creation of a small table representing five financial transactions

In [11]:
transactions = pd.DataFrame({
    "transation_id":["T001", "T002", "T003", "T004", "T005"],
    "customer_id":["C001", "C002", "C003", "C004", "C005"],
    "amount": [12.50, 8.00, 19.75, 4.20, 31.00],
    "currency": ["EUR", "EUR", "GBP", "EUR", "USD"]
})

transactions

  transation_id customer_id  amount currency
0          T001        C001   12.50      EUR
1          T002        C002    8.00      EUR
2          T003        C003   19.75      GBP
3          T004        C004    4.20      EUR
4          T005        C005   31.00      USD

## Initial inspection

Inspection of the dimensions, columns and data types of the dataframe

In [12]:
transactions.head()

  transation_id customer_id  amount currency
0          T001        C001   12.50      EUR
1          T002        C002    8.00      EUR
2          T003        C003   19.75      GBP
3          T004        C004    4.20      EUR
4          T005        C005   31.00      USD

In [13]:
transactions.shape

(5, 4)

In [14]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   transation_id  5 non-null      str
 1   customer_id    5 non-null      str
 2   amount         5 non-null      float64
 3   currency       5 non-null      str
dtypes: float64(1), str(3)
memory usage: 292.0 bytes

In [15]:
transactions.columns

Index(['transation_id', 'customer_id', 'amount', 'currency'], dtype='str')

In [16]:
transactions["amount"]

0    12.50
1     8.00
2    19.75
3     4.20
4    31.00
Name: amount, dtype: float64

In [17]:
transactions["amount"].mean()

np.float64(15.09)

In [18]:
transactions["amount"].sum()

np.float64(75.45)

## Loading the customers dataset

The customers dataset contains general information about the people using the financial service

In [19]:
from pathlib import Path

In [20]:
Path.cwd()

WindowsPath('c:/Users/Focus/Documents/GitHub/transaction-intelligence/notebooks')

In [21]:
current_directory = Path.cwd()

if current_directory.name == "notebooks":
    project_root = current_directory.parent
else:
    project_root = current_directory

project_root

WindowsPath('c:/Users/Focus/Documents/GitHub/transaction-intelligence')

In [22]:
customers_path = project_root / "data" / "raw" / "customers.csv"

customers_path

WindowsPath('c:/Users/Focus/Documents/GitHub/transaction-intelligence/data/raw/customers.csv')

In [23]:
customers_path.exists()

True

### Reading csv file

In [24]:
customers = pd.read_csv(customers_path)
customers

   customer_id  age      country signup_date customer_segment
0         C001   29        Spain  2023-01-15         Standard
1         C002   42        Spain  2022-06-03          Premium
2         C003   23       France  2024-02-11          Student
3         C004   35      Germany  2021-09-27          Premium
4         C005   31        Spain  2023-07-19         Standard
5         C006   54        Italy  2020-11-08          Premium
6         C007   27     Portugal  2024-05-22         Standard
7         C008   46        Spain  2022-02-14         Standard
8         C009   21  Netherlands  2025-01-10          Student
9         C010   38      Ireland  2021-04-30          Premium
10        C011   33        Spain  2023-10-05         Standard
11        C012   60       France  2019-12-18          Premium

### Customers data inspection

In [26]:
customers.head(3)

  customer_id  age country signup_date customer_segment
0        C001   29   Spain  2023-01-15         Standard
1        C002   42   Spain  2022-06-03          Premium
2        C003   23  France  2024-02-11          Student

In [27]:
customers.tail(3)

   customer_id  age  country signup_date customer_segment
9         C010   38  Ireland  2021-04-30          Premium
10        C011   33    Spain  2023-10-05         Standard
11        C012   60   France  2019-12-18          Premium

In [29]:
customers.shape

(12, 5)

In [30]:
customers.columns

Index(['customer_id', 'age', 'country', 'signup_date', 'customer_segment'], dtype='str')

In [31]:
customers.dtypes

customer_id           str
age                 int64
country               str
signup_date           str
customer_segment      str
dtype: object

><small> _Note: this project uses pandas 3.0 or later -> text columns are automatically inferred as str, while older pandas would display them as object_</small>

In [32]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       12 non-null     str
 1   age               12 non-null     int64
 2   country           12 non-null     str
 3   signup_date       12 non-null     str
 4   customer_segment  12 non-null     str
dtypes: int64(1), str(4)
memory usage: 612.0 bytes

In [33]:
customers.describe()

             age
count  12.000000
mean   36.583333
std    12.041280
min    21.000000
25%    28.500000
50%    34.000000
75%    43.000000
max    60.000000

In [34]:
customers.describe(include = "all")

       customer_id        age country signup_date customer_segment
count           12  12.000000      12          12               12
unique          12        NaN       7          12                3
top           C001        NaN   Spain  2023-01-15         Standard
freq             1        NaN       5           1                5
mean           NaN  36.583333     NaN         NaN              NaN
std            NaN  12.041280     NaN         NaN              NaN
min            NaN  21.000000     NaN         NaN              NaN
25%            NaN  28.500000     NaN         NaN              NaN
50%            NaN  34.000000     NaN         NaN              NaN
75%            NaN  43.000000     NaN         NaN              NaN
max            NaN  60.000000     NaN         NaN              NaN

In [35]:
customers["country"]

0           Spain
1           Spain
2          France
3         Germany
4           Spain
5           Italy
6        Portugal
7           Spain
8     Netherlands
9         Ireland
10          Spain
11         France
Name: country, dtype: str

In [36]:
customers["country"].value_counts()

country
Spain          5
France         2
Germany        1
Italy          1
Portugal       1
Netherlands    1
Ireland        1
Name: count, dtype: int64

# Accounts data exploration

The accounts dataset contains the financial accounts owned by the customers.
Each account belongs to one customer, while one customer may own multiple accounts

In [38]:
accounts_path = project_root / "data" / "raw" / "accounts.csv"
accounts_path

WindowsPath('c:/Users/Focus/Documents/GitHub/transaction-intelligence/data/raw/accounts.csv')

In [40]:
accounts_path.exists()

True

In [42]:
accounts = pd.read_csv(accounts_path)
accounts

   account_id customer_id account_type currency opening_date   status
0        A001        C001      Current      EUR   2023-01-16   Active
1        A002        C001      Savings      EUR   2023-03-01   Active
2        A003        C002      Current      EUR   2022-06-04   Active
3        A004        C002      Savings      USD   2022-07-15   Active
4        A005        C003      Current      EUR   2024-02-12   Active
5        A006        C004      Current      EUR   2021-09-28   Active
6        A007        C004      Savings      EUR   2022-01-10   Active
7        A008        C005      Current      EUR   2023-07-20   Active
8        A009        C006      Current      EUR   2020-11-09   Active
9        A010        C006      Savings      EUR   2021-02-20  Dormant
10       A011        C007      Current      EUR   2024-05-23   Active
11       A012        C008      Current      EUR   2022-02-15   Active
12       A013        C009      Current      EUR   2025-01-11   Active
13       A014        C010      Current      EUR   2021-05-01   Active
14       A015        C011      Current      EUR   2023-10-06   Active
15       A016        C012      Current      EUR   2019-12-19   Active

## Accounts data inspection

In [43]:
accounts.head(3)

  account_id customer_id account_type currency opening_date  status
0       A001        C001      Current      EUR   2023-01-16  Active
1       A002        C001      Savings      EUR   2023-03-01  Active
2       A003        C002      Current      EUR   2022-06-04  Active

In [44]:
accounts.tail(3)

   account_id customer_id account_type currency opening_date  status
13       A014        C010      Current      EUR   2021-05-01  Active
14       A015        C011      Current      EUR   2023-10-06  Active
15       A016        C012      Current      EUR   2019-12-19  Active

In [45]:
accounts.shape

(16, 6)

In [46]:
accounts.columns

Index(['account_id', 'customer_id', 'account_type', 'currency', 'opening_date',
       'status'],
      dtype='str')

In [47]:
accounts.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   account_id    16 non-null     str
 1   customer_id   16 non-null     str
 2   account_type  16 non-null     str
 3   currency      16 non-null     str
 4   opening_date  16 non-null     str
 5   status        16 non-null     str
dtypes: str(6)
memory usage: 900.0 bytes

In [48]:
accounts["account_type"].value_counts()

account_type
Current    12
Savings     4
Name: count, dtype: int64

In [49]:
accounts["customer_id"]

0     C001
1     C001
2     C002
3     C002
4     C003
5     C004
6     C004
7     C005
8     C006
9     C006
10    C007
11    C008
12    C009
13    C010
14    C011
15    C012
Name: customer_id, dtype: str

In [51]:
accounts[["account_id", "customer_id", "account_type"]]

   account_id customer_id account_type
0        A001        C001      Current
1        A002        C001      Savings
2        A003        C002      Current
3        A004        C002      Savings
4        A005        C003      Current
5        A006        C004      Current
6        A007        C004      Savings
7        A008        C005      Current
8        A009        C006      Current
9        A010        C006      Savings
10       A011        C007      Current
11       A012        C008      Current
12       A013        C009      Current
13       A014        C010      Current
14       A015        C011      Current
15       A016        C012      Current

In [53]:
type(accounts["customer_id"])

pandas.Series

In [54]:
type(accounts[["customer_id"]])

pandas.DataFrame

In [55]:
accounts.loc[accounts["customer_id"] == "C001"]

  account_id customer_id account_type currency opening_date  status
0       A001        C001      Current      EUR   2023-01-16  Active
1       A002        C001      Savings      EUR   2023-03-01  Active

In [56]:
accounts.loc[accounts["customer_id"] == "C001", ["account_id", "account_type", "currency"]]

  account_id account_type currency
0       A001      Current      EUR
1       A002      Savings      EUR

In [58]:
accounts.iloc[0:3, 0:2]

  account_id customer_id
0       A001        C001
1       A002        C001
2       A003        C002

In [60]:
accounts["customer_id"].isin(customers["customer_id"]).all()

np.True_

In [61]:
accounts["customer_id"].value_counts()

customer_id
C001    2
C002    2
C004    2
C006    2
C003    1
C005    1
C007    1
C008    1
C009    1
C010    1
C011    1
C012    1
Name: count, dtype: int64

## Initial account findings

- The dataset contains 16 accounts
- Some customers own more than one account
- Most accounts are current accounts
- Most accounts use EUR as their main currency
- One account is marked as dormant
- All accounts reference customers that exist in the customers database

# Merchants data exploration

The merchants dataset contains information about the businesses that receive transactions. Each merchant belongs to a business category and may operate either online or through a physical location

In [63]:
merchants_path = project_root / "data" / "raw" / "merchants.csv"
merchants_path

WindowsPath('c:/Users/Focus/Documents/GitHub/transaction-intelligence/data/raw/merchants.csv')

In [64]:
merchants_path.exists()

True

In [67]:
merchants = pd.read_csv(merchants_path)
merchants

   merchant_id   merchant_name       category      country  online
0         M001    Green Market      Groceries        Spain   False
1         M002    Urban Coffee    Restaurants        Spain   False
2         M003     Book Planet          Books        Spain    True
3         M004      Tech World    Electronics      Germany    True
4         M005    Fresh Basket      Groceries       France   False
5         M006     Cloud Store    Electronics      Ireland    True
6         M007        Fit Zone         Sports        Spain   False
7         M008      Travel Now         Travel  Netherlands    True
8         M009     Home Corner           Home     Portugal    True
9         M010  Cinema Central  Entertainment        Spain   False
10        M011    Style Avenue        Fashion        Italy    True
11        M012  Daily Pharmacy         Health        Spain   False
12        M013        Game Box  Entertainment       France    True
13        M014  Stationery Hub         Office        Spain    True
14        M015       Sun Hotel         Travel     Portugal   False

In [68]:
merchants.head()

  merchant_id merchant_name     category  country  online
0        M001  Green Market    Groceries    Spain   False
1        M002  Urban Coffee  Restaurants    Spain   False
2        M003   Book Planet        Books    Spain    True
3        M004    Tech World  Electronics  Germany    True
4        M005  Fresh Basket    Groceries   France   False

In [69]:
merchants.tail()

   merchant_id   merchant_name       category   country  online
10        M011    Style Avenue        Fashion     Italy    True
11        M012  Daily Pharmacy         Health     Spain   False
12        M013        Game Box  Entertainment    France    True
13        M014  Stationery Hub         Office     Spain    True
14        M015       Sun Hotel         Travel  Portugal   False

In [70]:
merchants.shape

(15, 5)

In [71]:
merchants.columns

Index(['merchant_id', 'merchant_name', 'category', 'country', 'online'], dtype='str')

In [72]:
merchants.dtypes

merchant_id       str
merchant_name     str
category          str
country           str
online           bool
dtype: object

In [73]:
merchants["online"]

0     False
1     False
2      True
3      True
4     False
5      True
6     False
7      True
8      True
9     False
10     True
11    False
12     True
13     True
14    False
Name: online, dtype: bool

In [74]:
merchants["online"].value_counts()

online
True     8
False    7
Name: count, dtype: int64

In [75]:
merchants["online"] == True

0     False
1     False
2      True
3      True
4     False
5      True
6     False
7      True
8      True
9     False
10     True
11    False
12     True
13     True
14    False
Name: online, dtype: bool

In [76]:
merchants.loc[merchants["online"]]

   merchant_id   merchant_name       category      country  online
2         M003     Book Planet          Books        Spain    True
3         M004      Tech World    Electronics      Germany    True
5         M006     Cloud Store    Electronics      Ireland    True
7         M008      Travel Now         Travel  Netherlands    True
8         M009     Home Corner           Home     Portugal    True
10        M011    Style Avenue        Fashion        Italy    True
12        M013        Game Box  Entertainment       France    True
13        M014  Stationery Hub         Office        Spain    True

In [77]:
merchants.loc[~merchants["online"]]

   merchant_id   merchant_name       category   country  online
0         M001    Green Market      Groceries     Spain   False
1         M002    Urban Coffee    Restaurants     Spain   False
4         M005    Fresh Basket      Groceries    France   False
6         M007        Fit Zone         Sports     Spain   False
9         M010  Cinema Central  Entertainment     Spain   False
11        M012  Daily Pharmacy         Health     Spain   False
14        M015       Sun Hotel         Travel  Portugal   False

In [78]:
merchants.loc[:, ["merchant_name", "category", "online"]]

     merchant_name       category  online
0     Green Market      Groceries   False
1     Urban Coffee    Restaurants   False
2      Book Planet          Books    True
3       Tech World    Electronics    True
4     Fresh Basket      Groceries   False
5      Cloud Store    Electronics    True
6         Fit Zone         Sports   False
7       Travel Now         Travel    True
8      Home Corner           Home    True
9   Cinema Central  Entertainment   False
10    Style Avenue        Fashion    True
11  Daily Pharmacy         Health   False
12        Game Box  Entertainment    True
13  Stationery Hub         Office    True
14       Sun Hotel         Travel   False

In [79]:
merchants["category"].unique()

<StringArray>
[    'Groceries',   'Restaurants',         'Books',   'Electronics',
        'Sports',        'Travel',          'Home', 'Entertainment',
       'Fashion',        'Health',        'Office']
Length: 11, dtype: str

In [80]:
merchants["category"].value_counts()

category
Groceries        2
Electronics      2
Travel           2
Entertainment    2
Restaurants      1
Books            1
Sports           1
Home             1
Fashion          1
Health           1
Office           1
Name: count, dtype: int64

In [81]:
merchants["category"].nunique()

11

In [82]:
merchants["country"].nunique()

7

In [83]:
merchants.loc[(merchants["country"] == "Spain") & (merchants["online"])]

   merchant_id   merchant_name category country  online
2         M003     Book Planet    Books   Spain    True
13        M014  Stationery Hub   Office   Spain    True

In [84]:
merchants.loc[(merchants["category"] == "Electronics") | (merchants["category"] == "Travel")]

   merchant_id merchant_name     category      country  online
3         M004    Tech World  Electronics      Germany    True
5         M006   Cloud Store  Electronics      Ireland    True
7         M008    Travel Now       Travel  Netherlands    True
14        M015     Sun Hotel       Travel     Portugal   False

In [85]:
merchants.sort_values("merchant_name")

   merchant_id   merchant_name       category      country  online
2         M003     Book Planet          Books        Spain    True
9         M010  Cinema Central  Entertainment        Spain   False
5         M006     Cloud Store    Electronics      Ireland    True
11        M012  Daily Pharmacy         Health        Spain   False
6         M007        Fit Zone         Sports        Spain   False
4         M005    Fresh Basket      Groceries       France   False
12        M013        Game Box  Entertainment       France    True
0         M001    Green Market      Groceries        Spain   False
8         M009     Home Corner           Home     Portugal    True
13        M014  Stationery Hub         Office        Spain    True
10        M011    Style Avenue        Fashion        Italy    True
14        M015       Sun Hotel         Travel     Portugal   False
3         M004      Tech World    Electronics      Germany    True
7         M008      Travel Now         Travel  Netherlands    True
1         M002    Urban Coffee    Restaurants        Spain   False

In [87]:
merchants.sort_values(["country", "category"])

   merchant_id   merchant_name       category      country  online
12        M013        Game Box  Entertainment       France    True
4         M005    Fresh Basket      Groceries       France   False
3         M004      Tech World    Electronics      Germany    True
5         M006     Cloud Store    Electronics      Ireland    True
10        M011    Style Avenue        Fashion        Italy    True
7         M008      Travel Now         Travel  Netherlands    True
8         M009     Home Corner           Home     Portugal    True
14        M015       Sun Hotel         Travel     Portugal   False
2         M003     Book Planet          Books        Spain    True
9         M010  Cinema Central  Entertainment        Spain   False
0         M001    Green Market      Groceries        Spain   False
11        M012  Daily Pharmacy         Health        Spain   False
13        M014  Stationery Hub         Office        Spain    True
1         M002    Urban Coffee    Restaurants        Spain   False
6         M007        Fit Zone         Sports        Spain   False

In [88]:
merchants.sort_values("merchant_name", ascending = False)

   merchant_id   merchant_name       category      country  online
1         M002    Urban Coffee    Restaurants        Spain   False
7         M008      Travel Now         Travel  Netherlands    True
3         M004      Tech World    Electronics      Germany    True
14        M015       Sun Hotel         Travel     Portugal   False
10        M011    Style Avenue        Fashion        Italy    True
13        M014  Stationery Hub         Office        Spain    True
8         M009     Home Corner           Home     Portugal    True
0         M001    Green Market      Groceries        Spain   False
12        M013        Game Box  Entertainment       France    True
4         M005    Fresh Basket      Groceries       France   False
6         M007        Fit Zone         Sports        Spain   False
11        M012  Daily Pharmacy         Health        Spain   False
5         M006     Cloud Store    Electronics      Ireland    True
9         M010  Cinema Central  Entertainment        Spain   False
2         M003     Book Planet          Books        Spain    True

In [89]:
merchants["merchant_id"].is_unique

True

In [90]:
merchants["merchant_id"].nunique()

15

In [91]:
len(merchants)

15

In [92]:
merchants.isna()

    merchant_id  merchant_name  category  country  online
0         False          False     False    False   False
1         False          False     False    False   False
2         False          False     False    False   False
3         False          False     False    False   False
4         False          False     False    False   False
5         False          False     False    False   False
6         False          False     False    False   False
7         False          False     False    False   False
8         False          False     False    False   False
9         False          False     False    False   False
10        False          False     False    False   False
11        False          False     False    False   False
12        False          False     False    False   False
13        False          False     False    False   False
14        False          False     False    False   False

In [93]:
merchants.isna().sum()

merchant_id      0
merchant_name    0
category         0
country          0
online           0
dtype: int64

In [95]:
merchant_summary = {
    "numer_of_merchants": len(merchants),
    "number_of_categories": merchants["category"].nunique(),
    "number_of_countries": merchants["country"].nunique(),
    "online_merchants": merchants["online"].sum(),
    "physical_merchants": (~merchants["online"]).sum()
}
merchant_summary

{'numer_of_merchants': 15,
 'number_of_categories': 11,
 'number_of_countries': 7,
 'online_merchants': np.int64(8),
 'physical_merchants': np.int64(7)}

## Initial merchants findings

- The dataset contains 15 merchants
- Merchants belong to several business categories and countries
- Some merchants operate online while others have physical locations
- Spain is the most represented merchant country
- The merchant identifiers are unique
- The dataset does not contain missing values