# Transaction data exploration

This notebook contains the initial exploration of the transaction dataset

## Objectives

- Verify that the development environment works correctly
- Review the basic structure of a pandas DataFrame
- Practise basic NumPy and pandas operations

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
print(f"NumPy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")

NumPy version: 2.5.0
Pandas version: 3.0.3

## First numpy array

Creation of a small array containing transactions amounts

In [9]:
amounts = np.array([12.50, 8.00, 19.75, 4.20, 31.00])
amounts

array([12.5 ,  8.  , 19.75,  4.2 , 31.  ])

In [10]:
amounts * 1.10

array([13.75 ,  8.8  , 21.725,  4.62 , 34.1  ])

## First pandas dataframe

Creation of a small table representing five financial transactions

In [11]:
transactions = pd.DataFrame({
    "transation_id":["T001", "T002", "T003", "T004", "T005"],
    "customer_id":["C001", "C002", "C003", "C004", "C005"],
    "amount": [12.50, 8.00, 19.75, 4.20, 31.00],
    "currency": ["EUR", "EUR", "GBP", "EUR", "USD"]
})

transactions

  transation_id customer_id  amount currency
0          T001        C001   12.50      EUR
1          T002        C002    8.00      EUR
2          T003        C003   19.75      GBP
3          T004        C004    4.20      EUR
4          T005        C005   31.00      USD

## Initial inspection

Inspection of the dimensions, columns and data types of the dataframe

In [12]:
transactions.head()

  transation_id customer_id  amount currency
0          T001        C001   12.50      EUR
1          T002        C002    8.00      EUR
2          T003        C003   19.75      GBP
3          T004        C004    4.20      EUR
4          T005        C005   31.00      USD

In [13]:
transactions.shape

(5, 4)

In [14]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   transation_id  5 non-null      str
 1   customer_id    5 non-null      str
 2   amount         5 non-null      float64
 3   currency       5 non-null      str
dtypes: float64(1), str(3)
memory usage: 292.0 bytes

In [15]:
transactions.columns

Index(['transation_id', 'customer_id', 'amount', 'currency'], dtype='str')

In [16]:
transactions["amount"]

0    12.50
1     8.00
2    19.75
3     4.20
4    31.00
Name: amount, dtype: float64

In [17]:
transactions["amount"].mean()

np.float64(15.09)

In [18]:
transactions["amount"].sum()

np.float64(75.45)

## Loading the customers dataset

The customers dataset contains general information about the people using the financial service

In [19]:
from pathlib import Path

In [20]:
Path.cwd()

WindowsPath('c:/Users/Focus/Documents/GitHub/transaction-intelligence/notebooks')

In [21]:
current_directory = Path.cwd()

if current_directory.name == "notebooks":
    project_root = current_directory.parent
else:
    project_root = current_directory

project_root

WindowsPath('c:/Users/Focus/Documents/GitHub/transaction-intelligence')

In [22]:
customers_path = project_root / "data" / "raw" / "customers.csv"

customers_path

WindowsPath('c:/Users/Focus/Documents/GitHub/transaction-intelligence/data/raw/customers.csv')

In [23]:
customers_path.exists()

True

### Reading csv file

In [24]:
customers = pd.read_csv(customers_path)
customers

   customer_id  age      country signup_date customer_segment
0         C001   29        Spain  2023-01-15         Standard
1         C002   42        Spain  2022-06-03          Premium
2         C003   23       France  2024-02-11          Student
3         C004   35      Germany  2021-09-27          Premium
4         C005   31        Spain  2023-07-19         Standard
5         C006   54        Italy  2020-11-08          Premium
6         C007   27     Portugal  2024-05-22         Standard
7         C008   46        Spain  2022-02-14         Standard
8         C009   21  Netherlands  2025-01-10          Student
9         C010   38      Ireland  2021-04-30          Premium
10        C011   33        Spain  2023-10-05         Standard
11        C012   60       France  2019-12-18          Premium

### Customers data inspection

In [26]:
customers.head(3)

  customer_id  age country signup_date customer_segment
0        C001   29   Spain  2023-01-15         Standard
1        C002   42   Spain  2022-06-03          Premium
2        C003   23  France  2024-02-11          Student

In [27]:
customers.tail(3)

   customer_id  age  country signup_date customer_segment
9         C010   38  Ireland  2021-04-30          Premium
10        C011   33    Spain  2023-10-05         Standard
11        C012   60   France  2019-12-18          Premium

In [29]:
customers.shape

(12, 5)

In [30]:
customers.columns

Index(['customer_id', 'age', 'country', 'signup_date', 'customer_segment'], dtype='str')

In [31]:
customers.dtypes

customer_id           str
age                 int64
country               str
signup_date           str
customer_segment      str
dtype: object

In [32]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       12 non-null     str
 1   age               12 non-null     int64
 2   country           12 non-null     str
 3   signup_date       12 non-null     str
 4   customer_segment  12 non-null     str
dtypes: int64(1), str(4)
memory usage: 612.0 bytes

In [33]:
customers.describe()

             age
count  12.000000
mean   36.583333
std    12.041280
min    21.000000
25%    28.500000
50%    34.000000
75%    43.000000
max    60.000000

In [34]:
customers.describe(include = "all")

       customer_id        age country signup_date customer_segment
count           12  12.000000      12          12               12
unique          12        NaN       7          12                3
top           C001        NaN   Spain  2023-01-15         Standard
freq             1        NaN       5           1                5
mean           NaN  36.583333     NaN         NaN              NaN
std            NaN  12.041280     NaN         NaN              NaN
min            NaN  21.000000     NaN         NaN              NaN
25%            NaN  28.500000     NaN         NaN              NaN
50%            NaN  34.000000     NaN         NaN              NaN
75%            NaN  43.000000     NaN         NaN              NaN
max            NaN  60.000000     NaN         NaN              NaN

In [35]:
customers["country"]

0           Spain
1           Spain
2          France
3         Germany
4           Spain
5           Italy
6        Portugal
7           Spain
8     Netherlands
9         Ireland
10          Spain
11         France
Name: country, dtype: str

In [36]:
customers["country"].value_counts()

country
Spain          5
France         2
Germany        1
Italy          1
Portugal       1
Netherlands    1
Ireland        1
Name: count, dtype: int64