# Transaction data exploration

This notebook contains the initial exploration of the transaction dataset

## Objectives

- Verify that the development environment works correctly
- Review the basic structure of a pandas DataFrame
- Practise basic NumPy and pandas operations

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
print(f"NumPy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")

NumPy version: 2.5.0
Pandas version: 3.0.3

## First numpy array

Creation of a small array containing transactions amounts

In [6]:
amounts = np.array([12.50, 8.00, 19.75, 4.20, 31.00])
amounts

array([12.5 ,  8.  , 19.75,  4.2 , 31.  ])

In [7]:
amounts * 1.10

array([13.75 ,  8.8  , 21.725,  4.62 , 34.1  ])

## First pandas dataframe

Creation of a small table representing five financial transactions

In [8]:
transactions = pd.DataFrame({
    "transation_id":["T001", "T002", "T003", "T004", "T005"],
    "customer_id":["C001", "C002", "C003", "C004", "C005"],
    "amount": [12.50, 8.00, 19.75, 4.20, 31.00],
    "currency": ["EUR", "EUR", "GBP", "EUR", "USD"]
})

transactions

  transation_id customer_id  amount currency
0          T001        C001   12.50      EUR
1          T002        C002    8.00      EUR
2          T003        C003   19.75      GBP
3          T004        C004    4.20      EUR
4          T005        C005   31.00      USD

## Initial inspection

Inspection of the dimensions, columns and data types of the dataframe

In [9]:
transactions.head()

  transation_id customer_id  amount currency
0          T001        C001   12.50      EUR
1          T002        C002    8.00      EUR
2          T003        C003   19.75      GBP
3          T004        C004    4.20      EUR
4          T005        C005   31.00      USD

In [11]:
transactions.shape

(5, 4)

In [12]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   transation_id  5 non-null      str
 1   customer_id    5 non-null      str
 2   amount         5 non-null      float64
 3   currency       5 non-null      str
dtypes: float64(1), str(3)
memory usage: 292.0 bytes

In [13]:
transactions.columns

Index(['transation_id', 'customer_id', 'amount', 'currency'], dtype='str')

In [14]:
transactions["amount"]

0    12.50
1     8.00
2    19.75
3     4.20
4    31.00
Name: amount, dtype: float64

In [15]:
transactions["amount"].mean()

np.float64(15.09)

In [16]:
transactions["amount"].sum()

np.float64(75.45)